### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by kuromon11** [kuromon11/chat-space#11]
#IPアドレス
18.180.52.33

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・文字色や大きさを調節しましょう！
[![Image from Gyazo](https://i.gyazo.com/2ef338c9abd3619a54f51294cbe8cdd9.png)](https://gyazo.com/2ef338c9abd3619a54f51294cbe8cdd9)

参照カリキュラム
https://master.tech-camp.in/curriculums/3944

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by kuromon11** [comment]
仕様書通りの修正をしました。
ご確認の程、お願いいたします。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
